# Kryptonim Stellar Integration
# SEP-1 Stellar Info File
# https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0001.md

VERSION="2.7.0"

# Network Configuration
# Using Stellar Mainnet (Production)
NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"

# Stellar Accounts controlled by Kryptonim
ACCOUNTS=[
"GCTGZRCR56RQWVRET2BHXNWQYJUEEUKW34BJQO2NCTAODPAFDFEEATRY"
]

SIGNING_KEY="GCTGZRCR56RQWVRET2BHXNWQYJUEEUKW34BJQO2NCTAODPAFDFEEATRY"

# Organization Documentation


# Primary Point of Contact
[[PRINCIPALS]]
